name = "FiniteElements2dDirichlet"
uuid = "246d098e-0122-4565-9ee7-68b1dc4e7a2c"
authors = ["João Victor Lopez Pereira"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
